# Generated by Django 3.1.7 on 2021-02-21 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_django_javascript', '0002_ajaxcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajaxcreate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
