# Generated by Django 3.1.7 on 2021-02-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django_javascript', '0007_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
